### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by Jasonjys** [awaisabir/MEANauth#1]
```
➜  MEANauth git:(master) ✗ npm start

> authenticationapp@1.0.0 start /Users/yjiang/MEANauth
> node app

Server listening on port : 3000
error mongodb://localhost:27017/auth
```

Cannot connect to mongodb after npm start. What did I miss?

**Comment by awaisabir** [comment]
Since the db is local, you have to start a local instance of Mongo. 
cd into your Mongo folder navigate to the bin and run mongod to run a local instance of Mongo. It will get rid of that error. 
The app is not complete so you can't do anything yet through the front end. You have to use POSTMAN to make calls to the endpoints.

**Comment by Jasonjys** [comment]
Fixed by creating a data/ folder and run mongod --dbpath=data. You can only do that when mongod is globally installed.
